# This workflow will attest and publish build artifacts ready for release

name: publish

on:
  push:
    branches: [main, master]

jobs:
  publish:
    runs-on: self-hosted
    permissions:
      contents: read
      id-token: write # required for provenance cert #https://docs.npmjs.com/generating-provenance-statements

    strategy:
      matrix:
        node-version: [20.x]

    timeout-minutes: 60 # Default 5 days for self hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        name: Use Node.js ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          # generates a '//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}'' >> .npmrc
      - run: npm ci
        
      - name: Build
        run: npm run ci:build

      - name: NPM Publish
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish ./dist --access public # --provenance # provenance requires a github hosted runner

      - name: Setup GH auth
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://npm.pkg.github.com'
      - name: GH Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish ./dist --access public # --provenance # provenance requires a github hosted runner
      - name: Set Version number
        run: echo "TAG=$(npm pkg get version --workspaces=false | tr -d \")" >> "$GITHUB_ENV"
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          tag_name: ${TAG}
          generate_release_notes: true
